### PR TITLE
Added examples for livestreaming and screensharing 📖

### PR DESCRIPTION
**Pull request by akshatvg**
# What to expect in this PR
- [x] Restructured examples folder to support new examples.
- [x] Added example for livestream.
- [x] Added example for screen sharing (solves #10).

### CODE REVIEW

**Comment by EkaanshArora** [comment]
Hey can you take a look at the following for screenshare example:
- decouple the screenshare logic
  - join button separated from screenshare
  - separate out end screenshare and endcall 
- local user should not subscribe to screenshare feed, only do track.play()
- getting some errors on joining (Client already in connecting/connected state & AgoraRTCError OPERATION_ABORTED: cancel token canceled)
Thank you

**Comment by demonzmahmood** [comment]
@akshatvg 
Hello ,
I tried your implementation for the share screen ,
it works well but when we stop the share screen we have to leave the channel then join again to start the share screen ,
the start/stop button doesn't work
did you solve it ?

thanks.

**Comment by MrFarhan** [comment]
Please merge this PR to Master.

Too many issues while integrating screen sharing during calls :(

**Review by muhamedoufi — APPROVED** [review]

**Comment by Unicodez-Github** [comment]
> Hey can you take a look at the following for screenshare example:
> 
> * decouple the screenshare logic
>   
>   * join button separated from screenshare
>   * separate out end screenshare and endcall
> * local user should not subscribe to screenshare feed, only do track.play()
> * getting some errors on joining (`Client already in connecting/connected state` & `AgoraRTCError OPERATION_ABORTED: cancel token canceled`)
> 
> Thanks!

Did the error got fixed ?

**Pull request closed without merging**
